// Mapeamento de ícones do VS Code Codicons
export const codicons = {
  files: 'codicon-files',
  search: 'codicon-search',
  sourceControl: 'codicon-source-control',
  debug: 'codicon-debug',
  extensions: 'codicon-extensions',
  newFile: 'codicon-new-file',
  folderOpen: 'codicon-folder-opened',
  folder: 'codicon-folder',
  file: 'codicon-file',
  code: 'codicon-code',
  link: 'codicon-link',
  listUnordered: 'codicon-list-unordered',
  graph: 'codicon-graph',
  edit: 'codicon-edit',
  splitHorizontal: 'codicon-split-horizontal',
  preview: 'codicon-preview',
  colorMode: 'codicon-color-mode',
  remote: 'codicon-remote',
  symbolString: 'codicon-symbol-string',
  bold: 'codicon-bold',
  italic: 'codicon-italic',
  heading: 'codicon-heading',
};
